#!/bin/bash

# Update system
sudo dnf update -y

# Install Apache
sudo dnf install httpd -y


mohit present

mohit absent
# Start Apache
sudo systemctl enable httpd
sudo systemctl start httpd

# Get IPs
PRIVATE_IP=$(hostname -I | awk '{print $1}')
PUBLIC_IP=$(curl -s http://checkip.amazonaws.com)
HOSTNAME=$(hostname)

# Create webpage
cat <<EOF > /var/www/html/index.html

<!DOCTYPE html>
<html>
<head>
<title>AWS Server Dashboard</title>

<style>
body{
background:#1e1e1e;
color:white;
font-family:Arial;
text-align:center;
}

.container{
margin-top:100px;
border:2px solid green;
width:60%;
margin-left:auto;
margin-right:auto;
padding:30px;
border-radius:15px;
box-shadow:0 0 20px green;
}

h1{
color:#00ff00;
}

.info{
font-size:24px;
padding:10px;
}
</style>

</head>

<body>

<div class="container">

<h1>EC2 SERVER DASHBOARD</h1>

<div class="info">Hostname : $HOSTNAME</div>

<div class="info">Private IP : $PRIVATE_IP</div>

<div class="info">Public IP : $PUBLIC_IP</div>

<div class="info">HTTPD Status : RUNNING</div>

</div>

</body>
</html>

EOF

